/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package trabajo.acumulativo;

/**
 *
 * @author yesner
 */
public class MDIPrincipal extends javax.swing.JFrame {

  /**
   * Creates new form MDIPrincipal
   */
  public MDIPrincipal() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        MenuEncuesta = new javax.swing.JMenuItem();
        MenuMayor = new javax.swing.JMenuItem();
        Menucuestionario = new javax.swing.JMenuItem();
        Menuempresa = new javax.swing.JMenuItem();
        Menupromedio = new javax.swing.JMenuItem();
        Menudescuento = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Trabajo");

        MenuEncuesta.setMnemonic('t');
        MenuEncuesta.setText("Encuenta");
        MenuEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEncuestaActionPerformed(evt);
            }
        });
        editMenu.add(MenuEncuesta);

        MenuMayor.setMnemonic('y');
        MenuMayor.setText("NumeroMayor");
        MenuMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMayorActionPerformed(evt);
            }
        });
        editMenu.add(MenuMayor);

        Menucuestionario.setMnemonic('p');
        Menucuestionario.setText("Cuestionario");
        Menucuestionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenucuestionarioActionPerformed(evt);
            }
        });
        editMenu.add(Menucuestionario);

        Menuempresa.setText("Empresa");
        Menuempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuempresaActionPerformed(evt);
            }
        });
        editMenu.add(Menuempresa);

        Menupromedio.setMnemonic('d');
        Menupromedio.setText("Promedio");
        Menupromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenupromedioActionPerformed(evt);
            }
        });
        editMenu.add(Menupromedio);

        Menudescuento.setText("Descuento");
        Menudescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenudescuentoActionPerformed(evt);
            }
        });
        editMenu.add(Menudescuento);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Acerca de");
        helpMenu.add(contentMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
      System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

  private void MenuEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEncuestaActionPerformed
    Frmencuesta M = new Frmencuesta();
    this.desktopPane.add(M);
    M.setVisible(true);
  }//GEN-LAST:event_MenuEncuestaActionPerformed

  private void MenuMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMayorActionPerformed
    FrmEvaluar E = new FrmEvaluar();
    this.desktopPane.add(E);
    E.setVisible(true);
  }//GEN-LAST:event_MenuMayorActionPerformed

  private void MenucuestionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenucuestionarioActionPerformed
    Frmcuestionario C = new Frmcuestionario();
    this.desktopPane.add(C);
    C.setVisible(true);
  }//GEN-LAST:event_MenucuestionarioActionPerformed

  private void MenupromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenupromedioActionPerformed
    FrmNotas N = new FrmNotas();
    this.desktopPane.add(N);
    N.setVisible(true);
  }//GEN-LAST:event_MenupromedioActionPerformed

  private void MenuempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuempresaActionPerformed
    Frmempresa e = new Frmempresa();
    this.desktopPane.add(e);
    e.setVisible(true);
  }//GEN-LAST:event_MenuempresaActionPerformed

  private void MenudescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenudescuentoActionPerformed
    Frmdescuento d = new Frmdescuento();
    this.desktopPane.add(d);
    d.setVisible(true);
  }//GEN-LAST:event_MenudescuentoActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MDIPrincipal().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuEncuesta;
    private javax.swing.JMenuItem MenuMayor;
    private javax.swing.JMenuItem Menucuestionario;
    private javax.swing.JMenuItem Menudescuento;
    private javax.swing.JMenuItem Menuempresa;
    private javax.swing.JMenuItem Menupromedio;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
